Adding accordion for dropdown children
code4recovery/tsml-ui pull request #430
Opened 2024-11-17 21:45 UTC by gkovats

Attempt to address the sub groups in dropdowns. Things to call out

- I used BEM style class names, maybe a departure from previous standard. Let me know if you want this changed / we're trying to keep class names to a minimum
- made the whole dropdown limit to 80% vertical heigh and scrollable, since dropdowns taller than the screen are kinda awful
- added mild animation for expand / collapse

![image](https://github.com/user-attachments/assets/824e0953-65b4-401a-bfac-c6d0e3a7db27)

2024-11-18 01:29 UTC, joshreisner commented
definitely seems like a good start, thanks! works well with many levels of nesting: https://deploy-preview-430--tsml-ui.netlify.app/tests/timezones.html?region=usa-new-york-manhattan-greenwich-village

noticed a few places where it seems like it could use some design polish:

* when a nested row is selected, the highlight does not go edge-to-edge

* looks like it's no longer shading on hover

* the other menus now have a lot of white space (before vs after), might be nice to try to keep the numbers flush right (as far as they'll go?) also maybe we need an internal border between items?
<img width="298" alt="before" src="https://github.com/user-attachments/assets/cd77d41d-d202-47c3-b315-eeb15aa96058">
<img width="299" alt="after" src="https://github.com/user-attachments/assets/76605336-8f27-489f-8199-91c0919f4833">

also some like very minor and subjective CSS notes - i'm happy to tweak some 

* feel like the triangles should be bigger, and animate when clicked, and respond somehow on hover, maybe by getting darker?

* the triangle gets lost in [dark mode](https://deploy-preview-430--tsml-ui.netlify.app/tests/aasanjose.html)
<img width="215" alt="Screenshot 2024-11-17 at 5 19 50 PM" src="https://github.com/user-attachments/assets/ed20d507-9592-49cc-b9b3-1a5b2c2c4ca0">

* also not sure why "San Jose" is wrapping in that case, i wonder if we could make the dropdowns go 100% wide when on mobile?

2024-12-28 18:49 UTC, gkovats commented
@joshreisner Another round.
- highlight is full width
- addressed the dark mode discrepancy
- made the triangle a smidge bigger. Really just reusing the other triangles for consistency, but can go with a chevron or something else
![image](https://github.com/user-attachments/assets/e4a11e6e-833b-4f7d-b18e-8966d1f11749)

2025-01-11 16:58 UTC, joshreisner requested changes
looks great thanks @gkovats ! just had some minor nits and one question if you don't mind

2025-01-11 16:58 UTC, joshreisner commented on src/styles/dropdown.ts
> +
sorry this is my fault - i actually shipped this change in a [recent PR](https://github.com/code4recovery/tsml-ui/commit/61df4c0d6900715e43f981f308c5f24c3917fe20#diff-58322c92a35f7d291218784c65e62e0bac9a65d3674f7923293a44ae69e824e4R13-R16), do you mind reverting this change?

2025-01-11 16:58 UTC, joshreisner commented on src/components/Dropdown.tsx
> +      if (e.metaKey || e.ctrlKey) {
what's this do? no objection per se  just wanted to understand. don't think this works on mac but maybe it does on windows or linux?

2025-01-11 16:58 UTC, joshreisner commented on src/styles/dropdown.ts
> +        //display: flex;
nbd but to follow conventions if you wouldn't mind sorting these lines (vscode has a "Sort Lines Ascending" option) and removing the commented properties

2025-01-11 17:59 UTC, gkovats commented on src/components/Dropdown.tsx
> +      if (e.metaKey || e.ctrlKey) {
"Meta" key is equal to what the rest of the world knows as a "Control" key. :)

2025-01-11 23:03 UTC, joshreisner approved these changes

2025-01-11 23:20 UTC, merged